### ISSUE TITLE
[Feature Request] Add Z axis and Rotation to the UI section and Rounded slider values

### ISSUE THREAD

**Issue by UrkiMimi** [Raz0rBeam/PlatformCustomizer#1]
Hi, I think both of these additions would be good to the mod as rounded slider values would make it easier to customize with the mod. Adding a Z axis along with Rotation for the UI would be a great thing as it allows for the mod to be more customizable.

Urki Mii❤

**Comment by Raz0rBeam** [comment]
If by x-axis you mean up and down, it won't work, all of it is a plane, except for the sides, so there's no depth. rotation on the z/y axis (i forgot unity is different than blender and should have named it better) would be possible, but im not sure why it would be necessary when you can put the scales to different sizes to emulate rotation. lastly I probably could make the sliders less precise, however I am lazy and would much rather put my time into adding new features, instead of changing it when it's not really broken. I will keep it in consideration though for later. Thank you for the feedback.
